Repository ReactRoad/React-Road, pull requests merged in 2023-05, with the labels that each got.

#9 2_3_jinhyi
  2&3/README.md
  2&3/index.html
  2&3/vanilla.html
  README.md
Labels: ⌨️Code

#6 2_3_seongmin
  README.md
  part2&3/README.md
  part2&3/index.html
  part2&3/vanilla.html
Labels: ⌨️Code

#11 4_5_youngchae
  youngchae/.gitignore
  youngchae/README.md
  youngchae/index.html
  youngchae/package-lock.json
  youngchae/package.json
  youngchae/public/favicon.ico
  youngchae/public/index.html
  youngchae/public/logo192.png
  youngchae/public/logo512.png
  youngchae/public/manifest.json
  youngchae/public/robots.txt
  youngchae/src/App.js
  youngchae/src/App.module.css
  youngchae/src/Button.js
  youngchae/src/Button.module.css
  youngchae/src/index.js
  youngchae/vanilla.html
Labels: ⌨️Code

#7 code : 2_3_part
  kyounghye/package-lock.json
  kyounghye/react-for-bdginners/.gitignore
  kyounghye/react-for-bdginners/README.md
  kyounghye/react-for-bdginners/package-lock.json
  kyounghye/react-for-bdginners/package.json
  kyounghye/react-for-bdginners/public/favicon.ico
  kyounghye/react-for-bdginners/public/index.html
  kyounghye/react-for-bdginners/public/logo192.png
  kyounghye/react-for-bdginners/public/logo512.png
  kyounghye/react-for-bdginners/public/manifest.json
  kyounghye/react-for-bdginners/public/robots.txt
  kyounghye/react-for-bdginners/src/App.css
  kyounghye/react-for-bdginners/src/App.js
  kyounghye/react-for-bdginners/src/App.test.js
  kyounghye/react-for-bdginners/src/index.css
  kyounghye/react-for-bdginners/src/index.js
  kyounghye/react-for-bdginners/src/logo.svg
  kyounghye/react-for-bdginners/src/reportWebVitals.js
  kyounghye/react-for-bdginners/src/setupTests.js
  kyounghye/react-for-bdginners/vanila.html
  kyounghye/react-movieweb/.gitignore
  kyounghye/react-movieweb/README.md
  kyounghye/react-movieweb/package-lock.json
  kyounghye/react-movieweb/package.json
  kyounghye/react-movieweb/public/favicon.ico
  kyounghye/react-movieweb/public/index.html
  kyounghye/react-movieweb/public/logo192.png
  kyounghye/react-movieweb/public/logo512.png
  kyounghye/react-movieweb/public/manifest.json
  kyounghye/react-movieweb/public/robots.txt
  kyounghye/react-movieweb/src/App.css
  kyounghye/react-movieweb/src/App.js
  kyounghye/react-movieweb/src/App.test.js
  kyounghye/react-movieweb/src/index.css
  kyounghye/react-movieweb/src/index.js
  kyounghye/react-movieweb/src/logo.svg
  kyounghye/react-movieweb/src/reportWebVitals.js
  kyounghye/react-movieweb/src/setupTests.js
Labels: ⌨️Code

#13 4_5_jinhyi
  4&5/README.md
  4&5/cra/.gitignore
  4&5/cra/README.md
  4&5/cra/package-lock.json
  4&5/cra/package.json
  4&5/cra/public/favicon.ico
  4&5/cra/public/index.html
  4&5/cra/public/logo192.png
  4&5/cra/public/logo512.png
  4&5/cra/public/manifest.json
  4&5/cra/public/robots.txt
  4&5/cra/src/App.js
  4&5/cra/src/App.module.css
  4&5/cra/src/Button.js
  4&5/cra/src/Button.module.css
  4&5/cra/src/index.js
  4&5/index.html
Labels: ⌨️Code

#16 6_7_jinhyi
  6&7/Coin/.gitignore
  6&7/Coin/README.md
  6&7/Coin/package-lock.json
  6&7/Coin/package.json
  6&7/Coin/public/favicon.ico
  6&7/Coin/public/index.html
  6&7/Coin/public/logo192.png
  6&7/Coin/public/logo512.png
  6&7/Coin/public/manifest.json
  6&7/Coin/public/robots.txt
  6&7/Coin/src/App.js
  6&7/Coin/src/index.js
  6&7/Movie/.gitignore
  6&7/Movie/README.md
  6&7/Movie/package-lock.json
  6&7/Movie/package.json
  6&7/Movie/public/favicon.ico
  6&7/Movie/public/index.html
  6&7/Movie/public/logo192.png
  6&7/Movie/public/logo512.png
  6&7/Movie/public/manifest.json
  6&7/Movie/public/robots.txt
  6&7/Movie/src/App.js
  6&7/Movie/src/components/Movie.js
  6&7/Movie/src/index.js
  6&7/Movie/src/routes/Detail.js
  6&7/Movie/src/routes/Home.js
  6&7/README.md
  6&7/ToDoList/.gitignore
  6&7/ToDoList/README.md
  6&7/ToDoList/package-lock.json
  6&7/ToDoList/package.json
  6&7/ToDoList/public/favicon.ico
  6&7/ToDoList/public/index.html
  6&7/ToDoList/public/logo192.png
  6&7/ToDoList/public/logo512.png
  6&7/ToDoList/public/manifest.json
  6&7/ToDoList/public/robots.txt
  6&7/ToDoList/src/App.js
  6&7/ToDoList/src/index.js
Labels: ⌨️Code

#17 feat : update readme
  part4&5/README.md
Labels: ⌨️Code

#14 6_7_youngchae
  youngchae/README.md
  youngchae/package-lock.json
  youngchae/package.json
  youngchae/src/App.js
  youngchae/src/App.module.css
  youngchae/src/Button.js
  youngchae/src/Button.module.css
  youngchae/src/Detail.css
  youngchae/src/components/Movie.js
  youngchae/src/index.js
  youngchae/src/routes/Detail.js
  youngchae/src/routes/Home.js
Labels: ⌨️Code

#20 2_3_haein
  haein/README.md
  haein/index.html
  haein/vanilla.html
  jinhyi/README.md
  kyounghye/README.md
  seongmin/README.md
  youngchae/README.md
Labels: ⌨️Code

#22 6_7_haein
  haein/index.html
  haein/react-for-beginners/.gitignore
  haein/react-for-beginners/README.md
  haein/react-for-beginners/package-lock.json
  haein/react-for-beginners/package.json
  haein/react-for-beginners/public/favicon.ico
  haein/react-for-beginners/public/index.html
  haein/react-for-beginners/public/logo192.png
  haein/react-for-beginners/public/logo512.png
  haein/react-for-beginners/public/manifest.json
  haein/react-for-beginners/public/robots.txt
  haein/react-for-beginners/src/App.js
  haein/react-for-beginners/src/App.module.css
  haein/react-for-beginners/src/Button.js
  haein/react-for-beginners/src/Button.module.css
  haein/react-for-beginners/src/components/Movie.js
  haein/react-for-beginners/src/index.js
  haein/react-for-beginners/src/routes/Detail.js
  haein/react-for-beginners/src/routes/Home.js
  haein/vanilla.html
Labels: ⌨️Code

#27 redux_youngchae
  youngchae/redux-101/README.md
  youngchae/redux-101/react-redux/react-redux-todo/.gitignore
  youngchae/redux-101/react-redux/react-redux-todo/README.md
  youngchae/redux-101/react-redux/react-redux-todo/package-lock.json
  youngchae/redux-101/react-redux/react-redux-todo/package.json
  youngchae/redux-101/react-redux/react-redux-todo/public/favicon.ico
  youngchae/redux-101/react-redux/react-redux-todo/public/index.html
  youngchae/redux-101/react-redux/react-redux-todo/public/logo192.png
  youngchae/redux-101/react-redux/react-redux-todo/public/logo512.png
  youngchae/redux-101/react-redux/react-redux-todo/public/manifest.json
  youngchae/redux-101/react-redux/react-redux-todo/public/robots.txt
  youngchae/redux-101/react-redux/react-redux-todo/src/components/App.js
  youngchae/redux-101/react-redux/react-redux-todo/src/index.js
  youngchae/redux-101/react-redux/react-redux-todo/src/routes/Detail.js
  youngchae/redux-101/react-redux/react-redux-todo/src/routes/Home.js
  youngchae/redux-101/react-redux/react-redux-todo/src/store.js
  youngchae/redux-101/vanilla-redux/vanilla-redux-counter/.gitignore
  youngchae/redux-101/vanilla-redux/vanilla-redux-counter/README.md
  youngchae/redux-101/vanilla-redux/vanilla-redux-counter/package-lock.json
  youngchae/redux-101/vanilla-redux/vanilla-redux-counter/package.json
  youngchae/redux-101/vanilla-redux/vanilla-redux-counter/public/favicon.ico
  youngchae/redux-101/vanilla-redux/vanilla-redux-counter/public/index.html
  youngchae/redux-101/vanilla-redux/vanilla-redux-counter/public/logo192.png
  youngchae/redux-101/vanilla-redux/vanilla-redux-counter/public/logo512.png
  youngchae/redux-101/vanilla-redux/vanilla-redux-counter/public/manifest.json
  youngchae/redux-101/vanilla-redux/vanilla-redux-counter/public/robots.txt
  youngchae/redux-101/vanilla-redux/vanilla-redux-counter/src/index.js
  youngchae/redux-101/vanilla-redux/vanilla-redux-todo/.gitignore
  youngchae/redux-101/vanilla-redux/vanilla-redux-todo/README.md
  youngchae/redux-101/vanilla-redux/vanilla-redux-todo/package-lock.json
  youngchae/redux-101/vanilla-redux/vanilla-redux-todo/package.json
  youngchae/redux-101/vanilla-redux/vanilla-redux-todo/public/favicon.ico
  youngchae/redux-101/vanilla-redux/vanilla-redux-todo/public/index.html
  youngchae/redux-101/vanilla-redux/vanilla-redux-todo/public/logo192.png
  youngchae/redux-101/vanilla-redux/vanilla-redux-todo/public/logo512.png
  youngchae/redux-101/vanilla-redux/vanilla-redux-todo/public/manifest.json
  youngchae/redux-101/vanilla-redux/vanilla-redux-todo/public/robots.txt
  youngchae/redux-101/vanilla-redux/vanilla-redux-todo/src/index.js
Labels: ⌨️Code, ✨Redux

#28 vanilla_redux_seongmin
  vanilla-redux/README.md
  vanilla-redux/counter/.gitignore
  vanilla-redux/counter/package-lock.json
  vanilla-redux/counter/package.json
  vanilla-redux/counter/public/favicon.ico
  vanilla-redux/counter/public/index.html
  vanilla-redux/counter/public/logo192.png
  vanilla-redux/counter/public/logo512.png
  vanilla-redux/counter/public/manifest.json
  vanilla-redux/counter/public/robots.txt
  vanilla-redux/counter/src/App.js
  vanilla-redux/counter/src/index.js
  vanilla-redux/todolist/.gitignore
  vanilla-redux/todolist/README.md
  vanilla-redux/todolist/package-lock.json
  vanilla-redux/todolist/package.json
  vanilla-redux/todolist/public/favicon.ico
  vanilla-redux/todolist/public/index.html
  vanilla-redux/todolist/public/logo192.png
  vanilla-redux/todolist/public/logo512.png
  vanilla-redux/todolist/public/manifest.json
  vanilla-redux/todolist/public/robots.txt
  vanilla-redux/todolist/src/App.js
  vanilla-redux/todolist/src/index.js
Labels: ⌨️Code, ✨Redux

#34 redux_jinhyi
  redux/README.md
  redux/react-redux/.gitignore
  redux/react-redux/README.md
  redux/react-redux/package-lock.json
  redux/react-redux/package.json
  redux/react-redux/public/favicon.ico
  redux/react-redux/public/index.html
  redux/react-redux/public/logo192.png
  redux/react-redux/public/logo512.png
  redux/react-redux/public/manifest.json
  redux/react-redux/public/robots.txt
  redux/react-redux/src/components/App.js
  redux/react-redux/src/components/ToDo.js
  redux/react-redux/src/index.js
  redux/react-redux/src/routes/Detail.js
  redux/react-redux/src/routes/Home.js
  redux/react-redux/src/store.js
  redux/vanilla-redux/counter/.gitignore
  redux/vanilla-redux/counter/README.md
  redux/vanilla-redux/counter/package-lock.json
  redux/vanilla-redux/counter/package.json
  redux/vanilla-redux/counter/public/favicon.ico
  redux/vanilla-redux/counter/public/index.html
  redux/vanilla-redux/counter/public/logo192.png
  redux/vanilla-redux/counter/public/logo512.png
  redux/vanilla-redux/counter/public/manifest.json
  redux/vanilla-redux/counter/public/robots.txt
  redux/vanilla-redux/counter/src/App.js
  redux/vanilla-redux/counter/src/index.js
  redux/vanilla-redux/todo/.gitignore
  redux/vanilla-redux/todo/README.md
  redux/vanilla-redux/todo/package-lock.json
  redux/vanilla-redux/todo/package.json
  redux/vanilla-redux/todo/public/favicon.ico
  redux/vanilla-redux/todo/public/index.html
  redux/vanilla-redux/todo/public/logo192.png
  redux/vanilla-redux/todo/public/logo512.png
  redux/vanilla-redux/todo/public/manifest.json
  redux/vanilla-redux/todo/public/robots.txt
  redux/vanilla-redux/todo/src/index.js
Labels: ⌨️Code, ✨Redux

#29 react_redux_seongmin
  part6&7/README.md
  part6&7/coin/README.md
  part6&7/coin/package-lock.json
  part6&7/coin/package.json
  part6&7/coin/public/index.html
  part6&7/coin/src/App.js
  part6&7/coin/src/index.js
  part6&7/effects/.gitignore
  part6&7/effects/README.md
  part6&7/effects/package-lock.json
  part6&7/effects/package.json
  part6&7/effects/public/favicon.ico
  part6&7/effects/public/index.html
  part6&7/effects/public/logo192.png
  part6&7/effects/public/logo512.png
  part6&7/effects/public/manifest.json
  part6&7/effects/public/robots.txt
  part6&7/effects/src/App.js
  part6&7/movie/.gitignore
  part6&7/movie/README.md
  part6&7/movie/public/favicon.ico
  part6&7/movie/public/index.html
  part6&7/movie/public/logo192.png
  part6&7/movie/public/logo512.png
  part6&7/movie/public/manifest.json
  part6&7/movie/public/robots.txt
  part6&7/movie/src/App.js
  part6&7/movie/src/components/Movie.js
  part6&7/movie/src/index.js
  part6&7/movie/src/routes/Detail.js
  part6&7/movie/src/routes/Home.js
  part6&7/to-do-list/.gitignore
  part6&7/to-do-list/README.md
  part6&7/to-do-list/package-lock.json
  part6&7/to-do-list/package.json
  part6&7/to-do-list/public/favicon.ico
  part6&7/to-do-list/public/index.html
  part6&7/to-do-list/public/logo192.png
  part6&7/to-do-list/public/logo512.png
  part6&7/to-do-list/public/manifest.json
  part6&7/to-do-list/public/robots.txt
  part6&7/to-do-list/src/App.js
  part6&7/to-do-list/src/index.js
  react-redux/.gitignore
  react-redux/README.md
  react-redux/package-lock.json
  react-redux/package.json
  react-redux/public/favicon.ico
  react-redux/public/index.html
  react-redux/public/logo192.png
  react-redux/public/logo512.png
  react-redux/public/manifest.json
  react-redux/public/robots.txt
  react-redux/src/components/App.js
  react-redux/src/components/ToDo.js
  react-redux/src/index.js
  react-redux/src/routes/Detail.js
  react-redux/src/routes/Home.js
  react-redux/src/store.js
Labels: ⌨️Code, ✨Redux

#37 3_kyounghye
  kyounghye/Redux101/react-redux/package-lock.json
  kyounghye/Redux101/react-redux/package.json
  kyounghye/Redux101/react-redux/src/App.css
  kyounghye/Redux101/react-redux/src/App.js
  kyounghye/Redux101/react-redux/src/App.test.js
  kyounghye/Redux101/react-redux/src/components/ToDo.js
  kyounghye/Redux101/react-redux/src/index.css
  kyounghye/Redux101/react-redux/src/index.js
  kyounghye/Redux101/react-redux/src/logo.svg
  kyounghye/Redux101/react-redux/src/reportWebVitals.js
  kyounghye/Redux101/react-redux/src/routes/Detail.js
  kyounghye/Redux101/react-redux/src/routes/Home.js
  kyounghye/Redux101/react-redux/src/routes/store.js
  kyounghye/Redux101/react-redux/src/setupTests.js
Labels: ⌨️Code, ✨Redux

#39 Movie_CSS_seongmin
  package-lock.json
  react-movie/.gitIgnore
  react-movie/README.old.md
  react-movie/package-lock.json
  react-movie/package.json
  react-movie/public/favicon.ico
  react-movie/public/index.html
  react-movie/public/logo192.png
  react-movie/public/logo512.png
  react-movie/public/manifest.json
  react-movie/public/robots.txt
  react-movie/src/App.css
  react-movie/src/App.js
  react-movie/src/components/CategoryNav.js
  react-movie/src/components/Detail.js
  react-movie/src/components/Loading.js
  react-movie/src/components/Movie.js
  react-movie/src/components/Navbar.js
  react-movie/src/index.js
  react-movie/src/routes/Category.js
  react-movie/src/routes/Home.js
  react-movie/src/routes/MovieDetail.js
  react-movie/src/routes/MovieHome.js
  react-movie/src/routes/styles.css
Labels: ✨React, 📹MovieWeb, ⌨️Code, 🖌️CSS
